SELECT * FROM empleados;
SELECT * FROM departamentos;
SELECT nombre_depto FROM departamentos GROUP BY nombre_depto;
SELECT nombre AS Nombre, sal_emp AS Salario FROM empleados;
SELECT comision_emp AS Comisión FROM empleados;
SELECT * FROM empleados WHERE cargo_emp = 'Secretaria';
SELECT * FROM empleados WHERE cargo_emp = 'Vendedor' ORDER BY nombre ASC;
SELECT nombre AS Nombre, cargo_emp AS Cargo, sal_emp AS Salario FROM empleados ORDER BY sal_emp ASC;
SELECT nombre_jefe_depto AS 'Nombre Jefe' FROM departamentos WHERE ciudad = 'Ciudad Real';
SELECT nombre AS Nombre, cargo_emp AS Cargo FROM empleados;
SELECT sal_emp AS Salario, comision_emp AS Comisión FROM empleados WHERE id_depto = 2000 ORDER BY comision_emp ASC;
SELECT nombre AS Nombre, sal_emp + comision_emp + 500 AS 'Pago Total' FROM empleados ORDER BY nombre ASC;
SELECT nombre AS Nombre FROM empleados WHERE nombre LIKE 'J%';
SELECT nombre AS Nombre, sal_emp AS Salario, comision_emp AS Comisión, sal_emp + comision_emp AS 'Salario Total' FROM empleados WHERE comision_emp > 1000;
SELECT nombre AS Nombre, sal_emp AS Salario, comision_emp AS Comisión, sal_emp + comision_emp AS 'Salario Total' FROM empleados WHERE comision_emp = 0 OR comision_emp = NULL;
SELECT nombre AS Nombre, sal_emp AS Salario, comision_emp AS Comisión FROM empleados WHERE comision_emp > sal_emp;
SELECT nombre AS Nombre FROM empleados WHERE comision_emp <= (sal_emp * 0.3);
SELECT nombre AS Nombre FROM empleados WHERE nombre NOT LIKE '%ma%';
SELECT nombre_depto AS Nombre FROM departamentos WHERE nombre_depto IN ('Ventas', 'Investigacion', 'Mantenimiento') GROUP BY nombre_depto;
SELECT nombre_depto AS Nombre FROM departamentos WHERE nombre_depto NOT IN ('Ventas', 'Investigacion', 'Mantenimiento') GROUP BY nombre_depto;
SELECT MAX(sal_emp) AS 'Mayor Salario' FROM empleados;
SELECT nombre AS Nombre FROM empleados ORDER BY nombre DESC LIMIT 1;
SELECT MAX(sal_emp) AS 'Salario Mayor', MIN(sal_emp) AS 'Salario Menor', MAX(sal_emp) - MIN(sal_emp) AS 'Diferencia' FROM empleados;
SELECT d.nombre_depto AS Nombre, AVG(e.sal_emp) AS Promedio FROM departamentos d JOIN empleados e ON d.id_depto = e.id_depto GROUP BY d.nombre_depto;
SELECT d.nombre_depto AS Nombre, COUNT(*) AS 'Cantidad Empleados' FROM departamentos d JOIN empleados e ON d.id_depto = e.id_depto GROUP BY nombre_depto HAVING COUNT(*) > 3;
SELECT d.id_depto AS ID, COUNT(*) AS 'Cantidad Empleados' FROM departamentos d JOIN empleados e ON d.id_depto = e.id_depto GROUP BY d.id_depto HAVING COUNT(*) = 0;
SELECT d.nombre_depto AS Departamento, e.nombre AS Nombre, e.sal_emp AS Salario FROM departamentos d JOIN empleados e ON d.id_depto = e.id_depto WHERE sal_emp >= (SELECT AVG(sal_emp) FROM empleados);