SELECT nombre FROM producto;
SELECT nombre, precio FROM producto;
SELECT * FROM producto;
SELECT nombre, ROUND(precio) FROM producto;
SELECT codigo_fabricante FROM producto;
SELECT DISTINCT codigo_fabricante FROM producto;
SELECT nombre FROM fabricante ORDER BY nombre ASC;
SELECT nombre, precio FROM producto ORDER BY nombre ASC, precio DESC;
SELECT * FROM fabricante LIMIT 5;
SELECT nombre, precio FROM producto ORDER BY precio ASC LIMIT 1;
SELECT nombre, precio FROM producto ORDER BY precio DESC LIMIT 1;
SELECT nombre, precio FROM producto WHERE precio <= 120;
SELECT nombre, precio FROM producto WHERE precio BETWEEN 60 AND 200;
SELECT codigo, nombre FROM producto WHERE codigo IN (1, 3, 5);
SELECT nombre FROM producto WHERE nombre LIKE '%portatil%';
SELECT p.codigo, p.nombre, f.* FROM fabricante f JOIN producto p ON f.codigo = p.codigo_fabricante;
SELECT p.nombre, p.precio, f.nombre FROM fabricante f JOIN producto p ON f.codigo = p.codigo_fabricante ORDER BY f.nombre ASC;
SELECT p.nombre, p.precio, f.nombre FROM fabricante f JOIN producto p ON f.codigo = p.codigo_fabricante WHERE precio = (SELECT MIN(precio) FROM producto);
SELECT p.nombre, f.nombre FROM fabricante f JOIN producto p ON f.codigo = p.codigo_fabricante WHERE f.nombre = 'Lenovo';
SELECT p.nombre, p.precio, f.nombre FROM fabricante f JOIN producto p ON f.codigo = p.codigo_fabricante WHERE f.nombre = 'Crucial' AND precio > 200;
SELECT p.nombre, f.nombre FROM fabricante f JOIN producto p ON f.codigo = p.codigo_fabricante WHERE f.nombre IN ('Asus', 'Hewlett-Packard');
SELECT p.nombre, p.precio, f.nombre FROM fabricante f JOIN producto p ON f.codigo = p.codigo_fabricante WHERE p.precio >= 180 ORDER BY p.precio DESC, p.nombre ASC;
SELECT f.nombre, p.nombre FROM fabricante f LEFT JOIN producto p ON f.codigo = p.codigo_fabricante;
SELECT f.nombre, p.nombre FROM fabricante f LEFT JOIN producto p ON f.codigo = p.codigo_fabricante WHERE p.codigo_fabricante IS NULL;
SELECT nombre FROM producto WHERE codigo_fabricante = (SELECT codigo FROM fabricante WHERE codigo = 2);
SELECT * FROM producto WHERE precio = (SELECT MAX(precio) FROM producto WHERE codigo_fabricante = 2);
SELECT nombre FROM producto WHERE precio = (SELECT MAX(precio) FROM producto WHERE codigo_fabricante = 2) AND codigo_fabricante = 2;
SELECT * FROM producto WHERE precio > (SELECT AVG(precio) FROM producto WHERE codigo_fabricante = 1) AND codigo_fabricante = 1;
SELECT nombre FROM fabricante WHERE codigo IN (SELECT codigo_fabricante FROM producto WHERE codigo_fabricante IS NOT NULL);
SELECT nombre FROM fabricante WHERE codigo NOT IN (SELECT codigo_fabricante FROM producto WHERE codigo_fabricante IS NOT NULL);
SELECT f.nombre, COUNT(*) FROM fabricante f JOIN producto p ON f.codigo = p.codigo_fabricante WHERE f.codigo != 2 GROUP BY f.nombre HAVING COUNT(*) = (SELECT COUNT(*) FROM producto WHERE codigo_fabricante = 2);